version: '3'

services:
  hc_front:
    build:
      context: ./
      dockerfile: Dockerfile
    image: homechallenge/front
    ports:
      - '8082:8082'
    environment:
      - SERVER_PORT=8082
      - API_URL=http://localhost:8081
